services:
  nuxt-static:
    image: nginx:alpine
    container_name: admin-portal-rhea
    restart: always
    ports:
      - '4000:80'
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
