services:
  nuxt-static:
    image: nginx:stable-alpine
    container_name: nuxt-static-site
    ports:
      - '3010:80'
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
